version: '3.2'
services: 
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/maxbrands.net:/var/www/html
    container_name: "frontend"
  
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    volumes:
      - /etc/letsencrypt/live/maxbrands.net:/root
    container_name: "backend"
